# Generated by Django 4.2.2 on 2023-06-12 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.CharField(choices=[('N', 'Norte'), ('NE', 'Nordeste'), ('S', 'Sul'), ('SE', 'Sudeste'), ('CO', 'Centro-Oeste')], max_length=2)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='capital_state', to='restAPI.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restAPI.state'),
        ),
    ]
