# Generated by Django 4.2.2 on 2023-06-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='city_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='capital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='capital_state', to='restAPI.city'),
        ),
    ]
