# Generated by Django 4.2.2 on 2023-06-13 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_state_abbreviation_state_city_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='capital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='capital_state', to='restAPI.city'),
        ),
    ]
