# Generated by Django 4.2.2 on 2023-06-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0005_alter_city_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
