# Generated by Django 4.2.2 on 2023-06-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0006_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
