# Generated by Django 4.2.2 on 2023-06-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0009_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
