# Generated by Django 4.2.2 on 2023-06-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0011_remove_player_name_remove_player_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restAPI.player'),
        ),
    ]
