# Generated by Django 4.2.2 on 2023-06-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0012_alter_gamescore_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.player'),
        ),
    ]
