# Generated by Django 4.2.2 on 2023-06-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0013_alter_gamescore_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
