# Generated by Django 4.2.2 on 2023-07-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0016_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='', max_length=16),
        ),
    ]
