# Generated by Django 4.2.2 on 2023-07-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0018_remove_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
