# Generated by Django 4.2.2 on 2023-07-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0020_player_bairro_player_cep_player_city_player_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cep',
            field=models.IntegerField(default=0, max_length=8),
        ),
    ]
