# Generated by Django 4.2.2 on 2023-07-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0021_alter_player_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cep',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
